// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrtm8fjg7vgR2g71lLUpJuZmzFLJTBR0',
    appId: '1:832097258875:web:233c5d00bef2c265e581de',
    messagingSenderId: '832097258875',
    projectId: 'job-timer-1-data',
    authDomain: 'job-timer-1-data.firebaseapp.com',
    storageBucket: 'job-timer-1-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0Nny0utTCyL_jlWWnuSum9be695YBqI',
    appId: '1:832097258875:android:bad2c52aa4f0775be581de',
    messagingSenderId: '832097258875',
    projectId: 'job-timer-1-data',
    storageBucket: 'job-timer-1-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZPIRJZarx4_8KWLvFE9YBf2tHo2_kKA',
    appId: '1:832097258875:ios:5a3e7972d7f79824e581de',
    messagingSenderId: '832097258875',
    projectId: 'job-timer-1-data',
    storageBucket: 'job-timer-1-data.appspot.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZPIRJZarx4_8KWLvFE9YBf2tHo2_kKA',
    appId: '1:832097258875:ios:f8876ea327230662e581de',
    messagingSenderId: '832097258875',
    projectId: 'job-timer-1-data',
    storageBucket: 'job-timer-1-data.appspot.com',
    iosBundleId: 'com.example.jobTimer.RunnerTests',
  );
}
